### ISSUE TITLE
Will indexes remain immutable?

### ISSUE THREAD

**Issue by drittich** [bleroy/lunr-core#13]
I noticed that lunr.js has decided on immutable indexes. Does lunr-core intend to adhere to this design goal? IMO, while feature parity with lunr.js is a laudable goal (and the point of this whole package even), the inability to add or remove individual documents reduces the usefulness of lunr-core server-side where lunr.js may not be used at all, and rebuilding the entire index for each document add/change/delete is not practical.

**Comment by bleroy** [comment]
Not necessarily. At this point it's a plain port so it does whatever lunr.js does.

**Comment by danielcrenna** [comment]
@drittich 

The mutable disk-based index (via LMDB) is merged to main, you can use it now and let me know what you think in terms of how to approach mutable documents. 

Right now, it can be used to persist pre-built indexes to disk for later referencing, and the data structures (fields, field vectors, and inverted index entries), can be added independently via `LmdbIndex`. 

I'm still thinking about how to rebalance the index efficiently when documents are added or removed, as rebuilding the entire thing doesn't get us much further along.
