### ISSUE TITLE
Add ability to serialize to alternate formats

### ISSUE THREAD

**Issue by danielcrenna** [bleroy/lunr-core#19]
**Is your feature request related to a problem? Please describe.**
I'd like to offload larger indexes so they don't require being present in memory via the Index type. For my use case, for example, I want to store the reverse indices, pipelines, vectors, etc., in LMDB, so that I only need to pull the relevant indices for a range of data records.

**Describe the solution you'd like**
I want the ability to "plug in" an alternate serialization interface that can defer lookups rather than require indices readily available from in-process memory.

**Additional context**
- I'm willing to do the work for this, but wanted to file a request first as it might not be a goal you have, as it's orthogonal to lunr.js' feature set.

**Comment by bleroy** [comment]
Sounds like a great feature. Totally agree it would be very useful.

**Comment by danielcrenna** [comment]
> Sounds like a great feature. Totally agree it would be very useful.

OK. I'll start picking away. Based on my first read-through, it seems this can be done in a separate "contrib" library, to keep the extensions separate from the main lunr code, but I could be wrong, when it comes to invoking the pipeline at query time, but I can least start with an alternate serialization that's disk-based and go from there. Most likely an alternate search extension method is required to do the deferred lookups.

**Comment by danielcrenna** [comment]
@bleroy sorry for the long delay on this -- I've had some time to look through the codebase, and it seems to me that the most tractable approach for alternate storage would be allowing the user to swap the currently fixed inproc `InvertedIndex` (which at the moment is just a converter-holding surrogate for serialization a dictionary), with an interface equivalent, and letting the user pass a custom one in the `Builder` ctor.

This way, logically anything that implements `IDictionary<string, InvertedIndexEntry>` could be plugged in there. I started an early draft of this here [https://github.com/danielcrenna/lunr-core/commit/c7e5d8dc3224b345946be55086fc8a7f6c5b7be4] for book-keeping and thoughts.

This puts the burden of an efficient alternative on the implementer of the dictionary interface, but it seems tractable (for example, implementing a fast-read LMDB dictionary is fairly trivial).

From here I think it is just implementing similar shims for fields, vectors, and tokens. 

Didn't want to get too far without you having a think.

**Comment by bleroy** [comment]
That sounds good. I’ll take a look at your draft but your description sounds fine. Thanks!
