### ISSUE TITLE
[FEATURE] Packaging LunrCoreLmdb for NuGet

### ISSUE THREAD

**Issue by danielcrenna** [bleroy/lunr-core#28]
**Is your feature request related to a problem? Please describe.**
We want to provide `LunrCoreLmdb` as an add-on NuGet package that takes a dependency on `LunrCore`.

**Describe the solution you'd like**
Ideally the NuGet packaging process would be added to the GitHub Actions CI, so that it can be managed from a single repository, versus having multiple maintainers of separate packages.

**Comment by bleroy** [comment]
https://www.nuget.org/packages/LunrCoreLmdb/2.3.8.5

**Comment by bleroy** [comment]
Let's consider automating the package publication for later. Until then, manual will do.
