### ISSUE TITLE
Invalid characters indexed

### ISSUE THREAD

**Issue by xoofx** [bleroy/lunr-core#3]
It seems that characters `/` (e.g `doc/advanc`) or `(` (e.g `bin(out`) are indexed with surrounding word characters.

**Comment by xoofx** [comment]
I saw that it the same in lunr.js (as you did a close port of it)

Using just space or hyphen seems so wrong to separate words, but maybe they expect a string to be squashed to these only? (so any other characters would have to be replaced by spaces before indexing?)

**Comment by bleroy** [comment]
Can you write down a few cases of the string to index, what it gets tokenized as, and what you'd expect?

**Comment by xoofx** [comment]
Closing as lunr is expecting only words and spaces/hyphen, I can workaround it on my side.
