### ISSUE TITLE
[BUG] Using the term presence feature doesn't work in some cases 

### ISSUE THREAD

**Issue by mozahr** [bleroy/lunr-core#47]
**To Reproduce**
making a search with term presence 'and' for example : "+dog +i" gives this error => **An item with the same key has already been added. Key: name'**

**Expected behavior**

**Comment by ziadakiki** [comment]
I second this, I had the same issue. The expected behavior IMO should be to take both words, "dog" and "i", use them and return results containing both words. Currently it is throwing the error mentioned above.

**Comment by bleroy** [comment]
Thanks for the report. I believe this is already fixed, I just need to publish a fixed package. I'll add a test and a fix soon if that's not the case.

**Comment by bleroy** [comment]
Fixed. Will publish a new package with the fix.
