### ISSUE TITLE
How to query position metadata?

### ISSUE THREAD

**Issue by xoofx** [bleroy/lunr-core#5]
In lunr.js, you can get the position of words returned on search by whitelisting `position`.

In LunrCore, if I use `builder.MetadataWhiteList` like this: 

```c#
            var index = Task.Run(() => Index.Build(async builder =>
            {
                builder.MetadataWhiteList.Add("position");
                builder.AddField("href", 3);
                builder.AddField("title", 2);
                builder.AddField("body", 1);

                foreach (var (file, plainText) in _searchContentList)
                {
                    await builder.Add(new Document
                    {
                        {"id", file.Url ?? string.Empty},
                        {"href", SquashPunctuation(file.Url ?? string.Empty)},
                        {"title", SquashPunctuation(file.Title ?? string.Empty)},
                        {"body", SquashPunctuation(plainText ?? string.Empty)},
                    });
                }
            })).Result;
```

I will get an exception on `builder.Add`:

```
System.Collections.Generic.KeyNotFoundException: 'The given key 'position' was not present in the dictionary.'
```

Not sure I'm using the library correctly in that case. What should I do to get the metadata 'position' serialized?

**Comment by bleroy** [comment]
Let me dig into that. You should definitely be able to get positions.

**Comment by bleroy** [comment]
Yes, so there's an easy bug there, and a testing oversight. Beyond that however, the metadata story in LunrCore is pretty sketchy at this point, because it relies so much on dynamic objects in lunr.js. I think this might lead me to some interesting refactoring...

**Comment by bleroy** [comment]
Aha, found it. Those pipeline functions are creating new tokens without keeping the metadata around (in addition to the easy bug above).
